#!/bin/sh

if [ -e ../zapish.inc ]; then
	. ../zapish.inc
elif [ -e /usr/libexec/zapish/zapish.inc ]; then
	. /usr/libexec/zapish/zapish.inc
else
	echo "No zapish.inc found"
	exit 1
fi

# Get all templates IDs
json_get "$(zabbix_api template.get \
	"$(json_list params \
		"$(json_str output extend \
		"")" \
	"")" \
)" '.result[].name' | \
while read template_name; do
	# strip down leading and trailing quotes
	template_name="${template_name:1:-1}"

	template_id="$(json_get "$(zabbix_api template.get \
		"$(json_list params \
			"$(json_list "filter" \
				"$(json_str "name" \
					"${template_name}" \
				"")" \
			"")" \
			"$(json_str "output" "simple" \
			"")" \
		"")" \
	)" '.result[].templateid')"

	xml_output="$(zabbix_api configuration.export \
		"$(json_list params \
			"$(json_list options \
				"$(json_array_num templates \
					${template_id} \
				"")" \
			"")" \
			"$(json_str format xml \
			"")" \
		"")" \
	)"

        #normalised_name=$(echo "${template_name}" | sed 's/ /_/g' | tr '[:upper:]' '[:lower:]')
        normalised_name="${template_name}"
	printf "Template id=%7s, Name=%-40s dump to \"%s.xml\"\n" ${template_id} "\"${normalised_name}\"" "${normalised_name}"
	echo "${xml_output}" | jq -r .result | xmllint --format - > "${normalised_name}.xml"
	#printf "Template id=%7s, Name=%-40s dump to \"%s.raw\"\n" ${template_id} "\"${template_name}\"" "${template_name}"
	#echo "${xml_output}" | jq .result > "${template_name}.raw"
done
